### ISSUE TITLE
RLI division just makes everything blue

### ISSUE THREAD

**Issue by john-judge** [john-judge/PhotoLib#16]
> RLI division just makes everything blue? 
(Scheuer, #15 )

First I tried checking that we keep as an image of floats since division results in near 0 values. Already done. 

Actually, the issue is that some of the RLI values in the corners are 1/100 the magnitude of those near the center, meaning that the RLI-divided image gets saturated at the low end and only the corners are high enough to be non-blue

![RLI_issue](https://user-images.githubusercontent.com/40705003/130512695-c80208ae-ff1b-42cf-8eab-f9b02324a8b2.png)
![RLI_variance_03_01_03](https://user-images.githubusercontent.com/40705003/130512697-add6caf8-d1d2-4443-a129-6236e8d37eb4.png)

@ksscheuer Moved this issue here to discuss. This is sort of along the lines of why I mentioned contrast normalization, though we don't have to go that extreme. 

Either we would want to crop the corners, or I'm thinking we would want to let the user adjust the contrast (keeping the contrast scale linear so as to not affect analysis). User would adjust the contrast range so that the interesting data is visible and the non-interesting data gets saturated out.

**Comment by ksscheuer** [comment]
I actually really like how this turned out. Looking at the traces, it's not counter-intuitive to me that the very dark pixels in the upper L corner have very high amplitude; they just also have very high noise (which is pretty common when you don't have enough light).

**Comment by john-judge** [comment]
Ok, I think this'll work. I see what you mean about how high SD could come into play, but for the example in the video we are just looking at Amp at Selected Frame / RLI

Closing this issue

**Comment by ksscheuer** [comment]
Right, I get that this is amplitude. I just mean that crazy high amplitude is actually a pretty normal problem for traces where you get a good response in an area with very low light intensity.

**Comment by john-judge** [comment]
Hmm, I don't know where 05-01-05 was pulled from, but here it is:

https://drive.google.com/file/d/1IdKh6Wrm5hevM1FwFrdOyPDuL566af2x/view?usp=drivesdk

**Comment by ksscheuer** [comment]
Yep, that looks right!
